version: '3.2'

services:

  letsencrypt-renew:
    image: certbot/certbot:latest
    container_name: letsencrypt-renew
    working_dir: /opt/certbot
    entrypoint: ["certbot"]
    command:
      - "renew"
      - "--webroot"
      - "-w"
      - "/html"
      - "--non-interactive"
      - "--agree-tos"
      - "--email"
      - "${CERTBOT_EMAIL}"
      - "-d"
      - "${CERTBOT_DOMAIN}"
      - "-v"
      - "${WEB_ROOT}:/html"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ./logs:/var/log/letsencrypt